export const COMPONENTS = [
  { name: 'Accordion', slug: 'accordion' },
  { name: 'Alert', slug: 'alert' },
  { name: 'Alert Dialog', slug: 'alert-dialog' },
  { name: 'Autocomplete', slug: 'autocomplete' },
  { name: 'Avatar', slug: 'avatar' },
  { name: 'Badge', slug: 'badge' },
  { name: 'Breadcrumb', slug: 'breadcrumb' },
  { name: 'Button', slug: 'button' },
  { name: 'Calendar', slug: 'calendar' },
  { name: 'Card', slug: 'card' },
  { name: 'Checkbox', slug: 'checkbox' },
  { name: 'Checkbox Group', slug: 'checkbox-group' },
  { name: 'Collapsible', slug: 'collapsible' },
  { name: 'Combobox', slug: 'combobox' },
  { name: 'Command', slug: 'command' },
  { name: 'Dialog', slug: 'dialog' },
  { name: 'Drawer', slug: 'drawer' },
  { name: 'Empty', slug: 'empty' },
  { name: 'Field', slug: 'field' },
  { name: 'Fieldset', slug: 'fieldset' },
  { name: 'Form', slug: 'form' },
  { name: 'Frame', slug: 'frame' },
  { name: 'Group', slug: 'group' },
  { name: 'Input', slug: 'input' },
  { name: 'Input Group', slug: 'input-group' },
  { name: 'Kbd', slug: 'kbd' },
  { name: 'Label', slug: 'label' },
  { name: 'Menu', slug: 'menu' },
  { name: 'Meter', slug: 'meter' },
  { name: 'Number Field', slug: 'number-field' },
  { name: 'Otp Field', slug: 'otp-field' },
  { name: 'Pagination', slug: 'pagination' },
  { name: 'Popover', slug: 'popover' },
  { name: 'Preview Card', slug: 'preview-card' },
  { name: 'Progress', slug: 'progress' },
  { name: 'Radio Group', slug: 'radio-group' },
  { name: 'Scroll Area', slug: 'scroll-area' },
  { name: 'Select', slug: 'select' },
  { name: 'Separator', slug: 'separator' },
  { name: 'Sheet', slug: 'sheet' },
  { name: 'Sidebar', slug: 'sidebar' },
  { name: 'Skeleton', slug: 'skeleton' },
  { name: 'Slider', slug: 'slider' },
  { name: 'Switch', slug: 'switch' },
  { name: 'Table', slug: 'table' },
  { name: 'Tabs', slug: 'tabs' },
  { name: 'Text', slug: 'text' },
  { name: 'Textarea', slug: 'textarea' },
  { name: 'Toast', slug: 'toast' },
  { name: 'Toggle', slug: 'toggle' },
  { name: 'Toggle Group', slug: 'toggle-group' },
  { name: 'Toolbar', slug: 'toolbar' },
  { name: 'Tooltip', slug: 'tooltip' },
] as const;
